### ISSUE TITLE
attribute error

### ISSUE THREAD

**Issue by Mcampbell10807** [alxgmpr/PyNode#2]
after fixing some of the other errors i was getting this ws next and i cant figure it out.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "main.py", line 426, in run
    self.generate_linode()
  File "main.py", line 142, in generate_linode
    client = linode.linodeclient(self.api_key)
AttributeError: 'module' object has no attribute 'linodeclient'

**Comment by ssega002** [comment]
Getting this same issue.. Have you figured it out?

**Comment by Mcampbell10807** [comment]
nah i havent

**Comment by alxgmpr** [comment]
I really don't know why this happens. It's something with the Linode API module. I saw it before when I installed 'linodeapi' instead of 'linode', which are different clients. But I only saw that issue when running with Python 3.
